CLASS zcl_17_handler DEFINITION PUBLIC
  FINAL CREATE PUBLIC
  FOR EVENTS OF z17_r_travel.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_17_HANDLER IMPLEMENTATION.
ENDCLASS.
